### ISSUE TITLE
Throwing response instead of error

### ISSUE THREAD

**Issue by Pagebakers** [cmdotcom/text-sdk-javascript#12]
The SDK is throwing the response when a request fails, while an error is expected.

```js
const send = async () => {
  try {
    const client = new CM.MessageApiClient('token')

    const result = await client.createMessage().send()
  } catch (e) {
    console.log(e) // this is a http response

    throw new Error(e.body.messages[0].messageErrorCode, e.body.messages[0].messageDetails)
  }
}
```

**Comment by joepb** [comment]
I agree with you there. 
It's not really a throwing an error, but I see the promise rejection is indeed returning a response object instead of an Error object as recommended. (see here)[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject]

https://github.com/cmdotcom/text-sdk-javascript/blob/43e2a12226cf48c8f511e89529fe84390a066504/typescript-node-client/api.ts#L1931

However, I think fixing this will be a very breaking change for implementations that now expect this behavior... 🤔

@EricSmekens , do you have an idea how to go about this without making the change a breaking one?

**Comment by EricSmekens** [comment]
If this is something we want, I would suggest making a breaking change and increase the version to 2.x.x.
It is part of the generated client-code, so we would have to look into the options when generating this.
Will look into that for the next update of this project.
